### ISSUE TITLE
create login page

### ISSUE THREAD

**Issue by sirAvent** [ctc-uci/get-inspired-frontend#14]
Create a bare bones skeleton of a login page.

**Comment by alanchangxyz** [comment]
actually I already made the common axios instance here but please make a common css file with all global styles including some starting color variables and base font(s) by consulting with design - you can reference ones in previous projects to see what should be defined globally and how it should be formatted/imported

**Comment by sirAvent** [comment]
Design has not decided on colors yet. Changed task to create a login page.
